// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SystemeNote.Data;

#nullable disable

namespace SystemeNote.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260104162400_AddUniqueColumnCodeEnseignement")]
    partial class AddUniqueColumnCodeEnseignement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SystemeNote.Models.Administrateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomAdmin")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nom_admin");

                    b.Property<string>("PrenomAdmin")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("prenom_admin");

                    b.HasKey("Id");

                    b.ToTable("administrateur");
                });

            modelBuilder.Entity("SystemeNote.Models.Config", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Valeur")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("valeur");

                    b.HasKey("Id");

                    b.ToTable("config");
                });

            modelBuilder.Entity("SystemeNote.Models.Diplome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomDiplome")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("NomDiplome")
                        .IsUnique();

                    b.ToTable("diplome");
                });

            modelBuilder.Entity("SystemeNote.Models.Etudiant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdministrateurId")
                        .HasColumnType("int")
                        .HasColumnName("administrateur_id");

                    b.Property<DateTime>("DateAdmission")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_admission");

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_naissance");

                    b.Property<int>("Genre")
                        .HasColumnType("int")
                        .HasColumnName("genre");

                    b.Property<bool>("IsActif")
                        .HasColumnType("bit")
                        .HasColumnName("is_actif");

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("matricule");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("mot_de_passe");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("nom");

                    b.Property<int>("PlanifSemestreId")
                        .HasColumnType("int")
                        .HasColumnName("planif_semestre_id");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("prenom");

                    b.Property<int>("PromotionId")
                        .HasColumnType("int")
                        .HasColumnName("promotion_id");

                    b.HasKey("Id");

                    b.HasIndex("AdministrateurId");

                    b.HasIndex("PlanifSemestreId");

                    b.HasIndex("PromotionId");

                    b.ToTable("etudiant");
                });

            modelBuilder.Entity("SystemeNote.Models.HistoriqueSemestreEtudiant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_debut");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_fin");

                    b.Property<int>("EtudiantId")
                        .HasColumnType("int")
                        .HasColumnName("etudiant_id");

                    b.Property<int>("PlanifSemetreId")
                        .HasColumnType("int")
                        .HasColumnName("planif_semetre_id");

                    b.HasKey("Id");

                    b.HasIndex("EtudiantId");

                    b.HasIndex("PlanifSemetreId");

                    b.ToTable("historique_semestre_etudiant");
                });

            modelBuilder.Entity("SystemeNote.Models.Matiere", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeMatiere")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("code_matiere");

                    b.Property<string>("NomMatiere")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nom_matiere");

                    b.HasKey("Id");

                    b.HasIndex("CodeMatiere")
                        .IsUnique();

                    b.HasIndex("NomMatiere")
                        .IsUnique();

                    b.ToTable("matiere");
                });

            modelBuilder.Entity("SystemeNote.Models.NoteEtudiant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EtudiantId")
                        .HasColumnType("int")
                        .HasColumnName("etudiant_id");

                    b.Property<double>("Note")
                        .HasColumnType("float")
                        .HasColumnName("note");

                    b.Property<int>("ParcoursEtudiantId")
                        .HasColumnType("int")
                        .HasColumnName("parcours_etudiant_id");

                    b.Property<int>("PromotionId")
                        .HasColumnType("int")
                        .HasColumnName("promotion_id");

                    b.HasKey("Id");

                    b.HasIndex("EtudiantId");

                    b.HasIndex("ParcoursEtudiantId");

                    b.HasIndex("PromotionId");

                    b.ToTable("note_etudiant");
                });

            modelBuilder.Entity("SystemeNote.Models.OptionEtude", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiplomeId")
                        .HasColumnType("int")
                        .HasColumnName("diplome_id");

                    b.Property<string>("NomOptionEtude")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nom_option_etude");

                    b.HasKey("Id");

                    b.HasIndex("DiplomeId");

                    b.ToTable("option_etude");
                });

            modelBuilder.Entity("SystemeNote.Models.ParcoursEtude", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MatiereId")
                        .HasColumnType("int")
                        .HasColumnName("matiere_id");

                    b.Property<int>("PlanifSemestreId")
                        .HasColumnType("int")
                        .HasColumnName("planif_semestre_id");

                    b.Property<int>("UniteEnseignementId")
                        .HasColumnType("int")
                        .HasColumnName("unite_enseignement_id");

                    b.HasKey("Id");

                    b.HasIndex("PlanifSemestreId");

                    b.HasIndex("UniteEnseignementId");

                    b.HasIndex("MatiereId", "UniteEnseignementId", "PlanifSemestreId")
                        .IsUnique();

                    b.ToTable("parcours_etude");
                });

            modelBuilder.Entity("SystemeNote.Models.PlanifSemestre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_debut");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_fin");

                    b.Property<string>("NomPlanifSemestre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nom_planif_semestre");

                    b.Property<int>("OptionEtudeId")
                        .HasColumnType("int")
                        .HasColumnName("option_etude_id");

                    b.Property<int>("PromotionId")
                        .HasColumnType("int")
                        .HasColumnName("promotion_id");

                    b.Property<int>("SemestreId")
                        .HasColumnType("int")
                        .HasColumnName("semestre_id");

                    b.Property<int>("TotalCredit")
                        .HasColumnType("int")
                        .HasColumnName("total_credit");

                    b.HasKey("Id");

                    b.HasIndex("OptionEtudeId");

                    b.HasIndex("PromotionId");

                    b.HasIndex("SemestreId");

                    b.ToTable("planif_semestre");
                });

            modelBuilder.Entity("SystemeNote.Models.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodePromotion")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateOnly>("DateCreation")
                        .HasColumnType("date");

                    b.Property<int>("DiplomeId")
                        .HasColumnType("int");

                    b.Property<string>("NomPromotion")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CodePromotion")
                        .IsUnique();

                    b.HasIndex("DiplomeId");

                    b.HasIndex("NomPromotion")
                        .IsUnique();

                    b.ToTable("promotion");
                });

            modelBuilder.Entity("SystemeNote.Models.Semestre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeSemestre")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("code_semestre");

                    b.Property<int>("DiplomeId")
                        .HasColumnType("int")
                        .HasColumnName("diplome_id");

                    b.Property<string>("NomSemestre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nom_semestre");

                    b.HasKey("Id");

                    b.HasIndex("CodeSemestre")
                        .IsUnique();

                    b.HasIndex("DiplomeId");

                    b.HasIndex("NomSemestre")
                        .IsUnique();

                    b.ToTable("semestre");
                });

            modelBuilder.Entity("SystemeNote.Models.UniteEnseignement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeUniteEnseignement")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("code_unite_enseignement");

                    b.Property<int>("Credits")
                        .HasColumnType("int")
                        .HasColumnName("credits");

                    b.HasKey("Id");

                    b.HasIndex("CodeUniteEnseignement")
                        .IsUnique();

                    b.ToTable("unite_enseignement");
                });

            modelBuilder.Entity("SystemeNote.Models.Etudiant", b =>
                {
                    b.HasOne("SystemeNote.Models.Administrateur", "Administrateur")
                        .WithMany("Etudiants")
                        .HasForeignKey("AdministrateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SystemeNote.Models.PlanifSemestre", "PlanifSemestre")
                        .WithMany("Etudiants")
                        .HasForeignKey("PlanifSemestreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SystemeNote.Models.Promotion", "Promotion")
                        .WithMany()
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Administrateur");

                    b.Navigation("PlanifSemestre");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("SystemeNote.Models.HistoriqueSemestreEtudiant", b =>
                {
                    b.HasOne("SystemeNote.Models.Etudiant", "Etudiant")
                        .WithMany("HistoriqueSemestreEtudiants")
                        .HasForeignKey("EtudiantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SystemeNote.Models.PlanifSemestre", "PlanifSemestre")
                        .WithMany("HistoriqueSemestreEtudiants")
                        .HasForeignKey("PlanifSemetreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Etudiant");

                    b.Navigation("PlanifSemestre");
                });

            modelBuilder.Entity("SystemeNote.Models.NoteEtudiant", b =>
                {
                    b.HasOne("SystemeNote.Models.Etudiant", "Etudiant")
                        .WithMany("NoteEtudiants")
                        .HasForeignKey("EtudiantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SystemeNote.Models.ParcoursEtude", "ParcoursEtude")
                        .WithMany("NoteEtudiants")
                        .HasForeignKey("ParcoursEtudiantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SystemeNote.Models.Promotion", "Promotion")
                        .WithMany()
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Etudiant");

                    b.Navigation("ParcoursEtude");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("SystemeNote.Models.OptionEtude", b =>
                {
                    b.HasOne("SystemeNote.Models.Diplome", "Diplome")
                        .WithMany()
                        .HasForeignKey("DiplomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diplome");
                });

            modelBuilder.Entity("SystemeNote.Models.ParcoursEtude", b =>
                {
                    b.HasOne("SystemeNote.Models.Matiere", "Matiere")
                        .WithMany("ParcoursEtudes")
                        .HasForeignKey("MatiereId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SystemeNote.Models.PlanifSemestre", "PlanifSemestre")
                        .WithMany("ParcoursEtudes")
                        .HasForeignKey("PlanifSemestreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SystemeNote.Models.UniteEnseignement", "UniteEnseignement")
                        .WithMany("ParcoursEtudes")
                        .HasForeignKey("UniteEnseignementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Matiere");

                    b.Navigation("PlanifSemestre");

                    b.Navigation("UniteEnseignement");
                });

            modelBuilder.Entity("SystemeNote.Models.PlanifSemestre", b =>
                {
                    b.HasOne("SystemeNote.Models.OptionEtude", "OptionEtude")
                        .WithMany("PlanifSemestres")
                        .HasForeignKey("OptionEtudeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SystemeNote.Models.Promotion", "Promotion")
                        .WithMany()
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SystemeNote.Models.Semestre", "Semestre")
                        .WithMany("PlanifSemestres")
                        .HasForeignKey("SemestreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OptionEtude");

                    b.Navigation("Promotion");

                    b.Navigation("Semestre");
                });

            modelBuilder.Entity("SystemeNote.Models.Promotion", b =>
                {
                    b.HasOne("SystemeNote.Models.Diplome", "Diplome")
                        .WithMany()
                        .HasForeignKey("DiplomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diplome");
                });

            modelBuilder.Entity("SystemeNote.Models.Semestre", b =>
                {
                    b.HasOne("SystemeNote.Models.Diplome", "Diplome")
                        .WithMany()
                        .HasForeignKey("DiplomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diplome");
                });

            modelBuilder.Entity("SystemeNote.Models.Administrateur", b =>
                {
                    b.Navigation("Etudiants");
                });

            modelBuilder.Entity("SystemeNote.Models.Etudiant", b =>
                {
                    b.Navigation("HistoriqueSemestreEtudiants");

                    b.Navigation("NoteEtudiants");
                });

            modelBuilder.Entity("SystemeNote.Models.Matiere", b =>
                {
                    b.Navigation("ParcoursEtudes");
                });

            modelBuilder.Entity("SystemeNote.Models.OptionEtude", b =>
                {
                    b.Navigation("PlanifSemestres");
                });

            modelBuilder.Entity("SystemeNote.Models.ParcoursEtude", b =>
                {
                    b.Navigation("NoteEtudiants");
                });

            modelBuilder.Entity("SystemeNote.Models.PlanifSemestre", b =>
                {
                    b.Navigation("Etudiants");

                    b.Navigation("HistoriqueSemestreEtudiants");

                    b.Navigation("ParcoursEtudes");
                });

            modelBuilder.Entity("SystemeNote.Models.Semestre", b =>
                {
                    b.Navigation("PlanifSemestres");
                });

            modelBuilder.Entity("SystemeNote.Models.UniteEnseignement", b =>
                {
                    b.Navigation("ParcoursEtudes");
                });
#pragma warning restore 612, 618
        }
    }
}
